(()=>{
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=d=>new Date(d).toLocaleString('fr-FR',{dateStyle:'short',timeStyle:'short'});
  const statusLabel={new:'Nouveau',in_progress:'En cours',done:'Fait',rejected:'Refusé'};
  const priorityLabel={low:'Faible',normal:'Normale',high:'Haute',urgent:'Urgente'};
  function getProfile(){try{return profile}catch(e){return null}}
  function getUser(){try{return user}catch(e){return null}}
  function getSb(){try{return sb}catch(e){return null}}
  function addStyle(){if(document.getElementById('ticketStyle'))return;const s=document.createElement('style');s.id='ticketStyle';s.textContent=`
    .tk-card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:18px;box-shadow:0 18px 45px rgba(15,23,42,.06);margin-bottom:14px}.tk-form{display:grid;grid-template-columns:2fr 1fr;gap:10px}.tk-form input,.tk-form select,.tk-form textarea,.tk-admin textarea,.tk-admin select{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:10px;background:#fff}.tk-form textarea{grid-column:1/-1;min-height:120px;resize:vertical}.tk-send{grid-column:1/-1;background:#d71920;color:#fff;border-color:#d71920}.tk-msg{font-size:11px;margin-top:8px;min-height:16px}.tk-list{display:grid;gap:10px}.tk-item{border:1px solid #e2e8f0;border-radius:14px;padding:13px;background:#fff}.tk-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.tk-head h3{margin:0 0 4px;font-size:15px}.tk-meta{font-size:10px;color:#64748b}.tk-badges{display:flex;gap:6px;flex-wrap:wrap}.tk-badge{font-size:10px;border-radius:999px;padding:4px 8px;background:#f1f5f9}.tk-desc{font-size:12px;line-height:1.5;white-space:pre-wrap;margin:10px 0}.tk-admin{display:grid;grid-template-columns:160px 1fr auto;gap:8px;align-items:start}.tk-save{background:#0f6b47;color:#fff;border-color:#0f6b47}.tk-empty{padding:18px;color:#64748b;text-align:center}.tk-count{display:inline-flex;min-width:20px;height:20px;padding:0 6px;align-items:center;justify-content:center;border-radius:999px;background:#d71920;color:#fff;font-size:10px;margin-left:auto}@media(max-width:800px){.tk-form,.tk-admin{grid-template-columns:1fr}.tk-form textarea,.tk-send{grid-column:auto}}
  `;document.head.appendChild(s)}
  function switchTo(){document.querySelectorAll('.rex-page').forEach(p=>p.classList.toggle('active',p.dataset.page==='tickets'));document.querySelectorAll('.rex-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page==='tickets'));load()}
  function mount(){
    const shell=document.getElementById('rexShellV3'),nav=shell?.querySelector('.rex-nav'),content=shell?.querySelector('.rex-content');if(!shell||!nav||!content)return false;if(document.getElementById('rexTicketsPage'))return true;addStyle();
    const btn=document.createElement('button');btn.dataset.page='tickets';btn.id='ticketNavBtn';btn.innerHTML='💡 Améliorations <span id="ticketCount" class="tk-count" style="display:none"></span>';btn.onclick=switchTo;const adminBtn=nav.querySelector('[data-page="admin"]');nav.insertBefore(btn,adminBtn||null);
    const page=document.createElement('section');page.className='rex-page';page.dataset.page='tickets';page.id='rexTicketsPage';page.innerHTML=`<div class="rex-page-head"><div><h2>Améliorations du logiciel</h2><p>Propose une amélioration et suis son traitement.</p></div></div><div class="tk-card"><h3 style="margin-top:0">Nouvelle demande</h3><div class="tk-form"><input id="tkTitle" maxlength="140" placeholder="Titre de la demande"><select id="tkPriority"><option value="low">Priorité faible</option><option value="normal" selected>Priorité normale</option><option value="high">Priorité haute</option><option value="urgent">Urgente</option></select><textarea id="tkDesc" maxlength="4000" placeholder="Explique précisément ce que tu voudrais améliorer, ajouter ou corriger…"></textarea><button id="tkSend" class="tk-send">Envoyer la demande</button></div><div id="tkMsg" class="tk-msg"></div></div><div class="tk-card"><h3 id="tkListTitle" style="margin-top:0">Mes demandes</h3><div id="tkList" class="tk-list"><div class="tk-empty">Chargement…</div></div></div>`;content.appendChild(page);
    page.querySelector('#tkSend').onclick=submit;loadBadge();return true;
  }
  async function submit(){const client=getSb(),u=getUser();if(!client||!u)return;const title=tkTitle.value.trim(),description=tkDesc.value.trim(),priority=tkPriority.value;if(title.length<3||description.length<5){tkMsg.textContent='Ajoute un titre et une description suffisamment précise.';return}tkSend.disabled=true;tkMsg.textContent='Envoi…';const r=await client.from('software_tickets').insert({user_id:u.id,title,description,priority});if(r.error){tkMsg.textContent='Erreur : '+r.error.message}else{tkTitle.value='';tkDesc.value='';tkPriority.value='normal';tkMsg.textContent='✓ Demande envoyée.';await load();await loadBadge()}tkSend.disabled=false}
  async function load(){const client=getSb(),p=getProfile();if(!client||!p)return;const q=await client.from('software_tickets').select('*').order('created_at',{ascending:false});if(q.error){tkList.innerHTML='<div class="tk-empty">Erreur : '+esc(q.error.message)+'</div>';return}let tickets=q.data||[],profiles={};if(p.role==='admin'){const pr=await client.from('profiles').select('user_id,display_name,sector_id');(pr.data||[]).forEach(x=>profiles[x.user_id]=x);tkListTitle.textContent='Toutes les demandes'}else tkListTitle.textContent='Mes demandes';render(tickets,profiles,p.role==='admin')}
  function render(tickets,profiles,isAdmin){tkList.innerHTML=tickets.length?tickets.map(t=>{const a=profiles[t.user_id],who=a?(a.display_name||'Vendeur')+(a.sector_id?' — Secteur '+a.sector_id:''):'Moi';return `<div class="tk-item"><div class="tk-head"><div><h3>${esc(t.title)}</h3><div class="tk-meta">${esc(who)} · ${fmt(t.created_at)}</div></div><div class="tk-badges"><span class="tk-badge">${priorityLabel[t.priority]||t.priority}</span><span class="tk-badge">${statusLabel[t.status]||t.status}</span></div></div><div class="tk-desc">${esc(t.description)}</div>${t.admin_note?`<div class="tk-meta"><b>Note admin :</b> ${esc(t.admin_note)}</div>`:''}${isAdmin?`<div class="tk-admin"><select data-status="${t.id}"><option value="new" ${t.status==='new'?'selected':''}>Nouveau</option><option value="in_progress" ${t.status==='in_progress'?'selected':''}>En cours</option><option value="done" ${t.status==='done'?'selected':''}>Fait</option><option value="rejected" ${t.status==='rejected'?'selected':''}>Refusé</option></select><textarea data-note="${t.id}" placeholder="Note admin…">${esc(t.admin_note||'')}</textarea><button class="tk-save" data-save="${t.id}">Enregistrer</button></div>`:''}</div>`}).join(''):'<div class="tk-empty">Aucune demande pour le moment.</div>';if(isAdmin)document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveTicket(b.dataset.save))}
  async function saveTicket(id){const client=getSb();const status=document.querySelector(`[data-status="${id}"]`).value,admin_note=document.querySelector(`[data-note="${id}"]`).value.trim();const r=await client.from('software_tickets').update({status,admin_note,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)alert(r.error.message);else{await load();await loadBadge()}}
  async function loadBadge(){const client=getSb(),p=getProfile();if(!client||!p||p.role!=='admin')return;const q=await client.from('software_tickets').select('id',{count:'exact',head:true}).eq('status','new');const n=q.count||0;const el=document.getElementById('ticketCount');if(el){el.textContent=n;el.style.display=n?'inline-flex':'none'}}
  let tries=0;const timer=setInterval(()=>{tries++;if(mount()||tries>120)clearInterval(timer)},250);setInterval(()=>{try{loadBadge()}catch(e){}},30000);window.addEventListener('load',()=>setTimeout(mount,900));
})();