(()=>{
  const BRAND='#d71920';
  function el(tag,attrs={},html=''){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?n.className=v:k.startsWith('data-')?n.setAttribute(k,v):n[k]=v);if(html)n.innerHTML=html;return n}
  function addStyle(){if(document.getElementById('rexUiV3Style'))return;const s=el('style',{id:'rexUiV3Style'});s.textContent=`
    :root{--rex-red:${BRAND};--rex-dark:#0f172a;--rex-muted:#64748b;--rex-line:#e2e8f0;--rex-bg:#f3f6fa;--rex-shadow:0 18px 45px rgba(15,23,42,.08)}
    body{background:var(--rex-bg)!important;color:#14243b}
    #forecastNav{display:none!important}
    .rex-shell{display:grid;grid-template-columns:248px minmax(0,1fr);min-height:100vh}
    .rex-side{background:linear-gradient(180deg,#0f172a,#162946);color:#fff;padding:20px 16px;display:flex;flex-direction:column;gap:18px;box-shadow:12px 0 36px rgba(15,23,42,.14)}
    .rex-brand{display:flex;align-items:center;gap:10px;padding:6px 6px 16px;border-bottom:1px solid rgba(255,255,255,.12)}
    .rex-logo{background:${BRAND};color:#fff;border-radius:8px;padding:8px 11px;font-size:18px;font-weight:900;letter-spacing:-.7px;white-space:nowrap}
    .rex-brand small{display:block;color:rgba(255,255,255,.68);font-size:10px;margin-top:3px;line-height:1.3}
    .rex-nav{display:flex;flex-direction:column;gap:7px}
    .rex-nav button{border:0;background:transparent;color:#e5e7eb;text-align:left;padding:12px 13px;border-radius:11px;font-weight:800;display:flex;gap:10px;align-items:center}
    .rex-nav button:hover{background:rgba(255,255,255,.08);filter:none}.rex-nav button.active{background:#fff;color:#0f172a;box-shadow:0 10px 24px rgba(0,0,0,.18)}
    .rex-main{min-width:0;display:flex;flex-direction:column}
    .rex-top{position:sticky;top:0;z-index:6000;background:rgba(255,255,255,.9);backdrop-filter:blur(10px);border-bottom:1px solid var(--rex-line);padding:14px 20px;display:flex;align-items:center;justify-content:space-between;gap:14px}
    .rex-title strong{font-size:19px;color:#0f172a}.rex-title span{display:block;color:var(--rex-muted);font-size:11px;margin-top:2px}
    .rex-content{padding:18px;min-width:0}.rex-page{display:none}.rex-page.active{display:block}
    .rex-page-head{display:flex;justify-content:space-between;align-items:flex-end;gap:12px;margin-bottom:14px}.rex-page-head h2{margin:0;font-size:24px;color:#0f172a}.rex-page-head p{margin:5px 0 0;font-size:12px;color:var(--rex-muted)}
    .rex-map-card,.rex-sector-card{background:#fff;border:1px solid var(--rex-line);border-radius:20px;box-shadow:var(--rex-shadow);overflow:hidden}
    #rexMapPage .stage{padding:0!important;height:auto!important;overflow:visible!important}#rexMapPage .board{min-width:0!important;border:0!important;border-radius:20px!important;box-shadow:none!important;min-height:760px!important}#rexMapPage .maparea{min-height:700px!important}
    #rexSectorPage .panel{border:0!important;box-shadow:none!important;width:100%!important;padding:18px!important;overflow:visible!important;background:#fff!important}
    #rexSectorPage .card{border-radius:16px!important;border:1px solid var(--rex-line)!important;box-shadow:0 8px 22px rgba(15,23,42,.04)!important}
    #rexSectorPage .counts{grid-template-columns:repeat(4,minmax(0,1fr))!important}.rex-see-map{width:100%;margin-top:9px;background:#0f172a;color:#fff;border-color:#0f172a}
    .rex-grid-note{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:14px}.rex-kpi{background:#fff;border:1px solid var(--rex-line);border-radius:16px;padding:14px;box-shadow:var(--rex-shadow)}.rex-kpi b{display:block;font-size:22px;color:#0f172a}.rex-kpi span{font-size:11px;color:var(--rex-muted)}
    #weeklyForecast{padding:0!important;background:transparent!important;min-height:0!important}#weeklyForecast.open{display:block!important}.wf-card,.wf-kpi{border-radius:16px!important;box-shadow:0 8px 22px rgba(15,23,42,.05)}
    .rex-placeholder{background:#fff;border:1px solid var(--rex-line);border-radius:18px;padding:22px;box-shadow:var(--rex-shadow);color:var(--rex-muted);line-height:1.55}
    .userbar{margin:0!important;min-width:275px;background:#fff!important;border:1px solid var(--rex-line)!important;border-radius:14px!important}.userbar button{background:#0f172a!important;color:#fff!important;border-color:#0f172a!important}
    body.seller .rex-admin-only,body.seller-mode .rex-admin-only{display:none!important}
    @media(max-width:1050px){.rex-shell{grid-template-columns:1fr}.rex-side{position:sticky;top:0;z-index:7000;padding:10px}.rex-brand{display:none}.rex-nav{flex-direction:row;overflow:auto}.rex-nav button{white-space:nowrap}.rex-top{position:static}.rex-content{padding:12px}#rexSectorPage .counts{grid-template-columns:repeat(2,1fr)!important}.rex-grid-note{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  function switchPage(name){document.querySelectorAll('.rex-page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('.rex-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='weekly'&&window.loadWeeklyForecast)window.loadWeeklyForecast();if(name==='map'&&typeof renderMap==='function')setTimeout(()=>renderMap(),20)}
  function mount(){if(document.getElementById('rexShellV3'))return true;const app=document.querySelector('.app');const panel=app?.querySelector('.panel');const stage=app?.querySelector('.stage');if(!app||!panel||!stage)return false;addStyle();
    const shell=el('div',{class:'rex-shell',id:'rexShellV3'});const side=el('aside',{class:'rex-side'});side.innerHTML=`<div class="rex-brand"><div class="rex-logo">Rex-Rotary</div><div><b>Pilotage Corrèze</b><small>Application commerciale agence</small></div></div><div class="rex-nav"><button data-page="dashboard">🏠 Tableau de bord</button><button data-page="map" class="active">🗺️ Carte</button><button data-page="sectors">📍 Secteurs</button><button data-page="weekly">📅 Prévisions semaine</button><button data-page="monthly">📈 Prévisions mensuelles</button><button class="rex-admin-only" data-page="admin">👥 Administration</button></div><div style="margin-top:auto;font-size:10px;color:rgba(255,255,255,.55);padding:6px">Rex-Rotary Corrèze • V3</div>`;
    const main=el('div',{class:'rex-main'}),top=el('header',{class:'rex-top'}),title=el('div',{class:'rex-title'},'<strong>Pilotage commercial Corrèze</strong><span>Carte, secteurs et prévisions commerciales</span>');const ub=document.getElementById('userbar')||document.getElementById('userBar');top.append(title);if(ub)top.append(ub);const content=el('div',{class:'rex-content'});
    const dash=el('section',{class:'rex-page','data-page':'dashboard'},'<div class="rex-page-head"><div><h2>Tableau de bord</h2><p>Vue synthétique de l’agence.</p></div></div><div class="rex-grid-note"><div class="rex-kpi"><b>4</b><span>Secteurs commerciaux</span></div><div class="rex-kpi"><b>19</b><span>Département Corrèze</span></div><div class="rex-kpi"><b>Cloud</b><span>Données synchronisées</span></div></div><div class="rex-placeholder">Le tableau de bord accueillera ensuite tes indicateurs agence et les statistiques de vente.</div>');
    const mapPage=el('section',{class:'rex-page active',id:'rexMapPage','data-page':'map'});mapPage.innerHTML='<div class="rex-page-head"><div><h2>Carte commerciale</h2><p>Visualisation géographique des secteurs S1 à S4 sur la Corrèze.</p></div></div>';const mapCard=el('div',{class:'rex-map-card'});mapCard.append(stage);mapPage.append(mapCard);
    const sectorPage=el('section',{class:'rex-page',id:'rexSectorPage','data-page':'sectors'});sectorPage.innerHTML='<div class="rex-page-head"><div><h2>Secteurs</h2><p>Codes postaux, affectations, vendeurs et potentiel commercial.</p></div></div>';const secCard=el('div',{class:'rex-sector-card'});secCard.append(panel);sectorPage.append(secCard);
    const weeklyPage=el('section',{class:'rex-page','data-page':'weekly'});weeklyPage.innerHTML='<div class="rex-page-head"><div><h2>Prévisions semaine</h2><p>Affaires prévues à la signature par vendeur.</p></div></div>';const wf=document.getElementById('weeklyForecast');if(wf){wf.classList.add('open');weeklyPage.append(wf)}else weeklyPage.append(el('div',{class:'rex-placeholder'},'Chargement du module de prévisions semaine…'));
    const monthly=el('section',{class:'rex-page','data-page':'monthly'},'<div class="rex-page-head"><div><h2>Prévisions mensuelles</h2><p>Projection mensuelle de l’agence et par vendeur.</p></div></div><div class="rex-placeholder">Ce module sera développé après validation du fonctionnement hebdomadaire.</div>');
    const admin=el('section',{class:'rex-page rex-admin-only','data-page':'admin'},'<div class="rex-page-head"><div><h2>Administration</h2><p>Gestion des vendeurs et des accès.</p></div></div><div class="rex-placeholder">La création des vendeurs reste disponible dans Secteurs. Nous pourrons ensuite centraliser ici la liste des comptes et leurs droits.</div>');
    content.append(dash,mapPage,sectorPage,weeklyPage,monthly,admin);main.append(top,content);shell.append(side,main);app.replaceWith(shell);const oldNav=document.getElementById('forecastNav');if(oldNav)oldNav.remove();document.querySelectorAll('.rex-nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));
    const selected=document.getElementById('selected');if(selected&&!document.getElementById('rexSeeMap')){const btn=el('button',{id:'rexSeeMap',class:'rex-see-map'},'Voir sur la carte');btn.onclick=()=>switchPage('map');selected.insertAdjacentElement('afterend',btn)}
    return true
  }
  let tries=0;const timer=setInterval(()=>{tries++;if(mount()||tries>100)clearInterval(timer)},180);window.addEventListener('load',()=>setTimeout(mount,250));
})();